INSERT INTO topic (name) VALUES
                             ('Typescript'),
                             ('Javascript'),
                             ('Java'),
                             ('Rust'),
                             ('Python'),
                             ('C'),
                             ('C#'),
                             ('C++'),
                             ('Ruby'),
                             ('Ada'),
                             ('Eiffel'),
                             ('ASP.NET'),
                             ('BASIC'),
                             ('Caml'),
                             ('Common Lisp'),
                             ('Coq'),
                             ('CSS'),
                             ('Dart'),
                             ('Fortran'),
                             ('Go'),
                             ('Kotlin'),
                             ('Lua'),
                             ('Pascal'),
                             ('Perl'),
                             ('PHP'),
                             ('Windows Powershell'),
                             ('shell'),
                             ('Prolog'),
                             ('Scala'),
                             ('Smalltalk'),
                             ('Swift'),
                             ('Powershell'),
                             ('Visual Basic .NET');